services:
  task-runners:
    image: n8nio/runners:2.1.5
    environment:
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
      - N8N_RUNNERS_TASK_BROKER_URI=${N8N_RUNNERS_TASK_BROKER_URI}
      - N8N_RUNNERS_LAUNCHER_LOG_LEVEL=debug
      - N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT=15
